### ISSUE TITLE
Custom table view

### ISSUE THREAD

**Issue by mfallq** [Alvinger/MMM-ResRobot#1]
Hi!

I would like to write out full text of some fields in my table, right now I'm using your module to show ferry departures. Its working but I want to show the full name of the "lineno" and "to" fields. Right now it says "Älvsna" instead of Älvsnabben and "Lilla" instead of Lilla Bommen as I want it to be. Tried to search among the module files but I cannot find where this can be modified. 

Best regards

**Comment by Alvinger** [comment]
Hi,
Just change the value of "truncateAfter" to 0 (zero) and it will work as expected. Any other value than zero will truncate the text. It is all in the README.
