### ISSUE TITLE
Stuck on Fetching, when sudo reboot black screen

### ISSUE THREAD

**Issue by teddzoon** [Alvinger/MMM-ResRobot#16]
Hi, 
Have dibbled with my MM for a while and wanted to add the busstop on the road.
Installed this module and took the config from readme, updated with a api-key (worked in this test https://api.resrobot.se/v2/departureBoard?key=<DIN NYCKEL>&id=<HÅLLPLATSID>&maxJourneys=<MAX ANTAL SVAR>).

When i add the config in MM, it gets stuck on "Fetching departures". After a Sudo reboot, MagicMiror does not load, and all I get is a black screen with a cursor.
I only changed API key and Station ID 

If I remove config of module, MM works again.

```
	{
		module: "MMM-ResRobot",
		position: "top_right",
		header: "Departures",
		config: {
			routes: [
				{from: "740075694", to: ""},	// ResRobot Station IDs of starting and destination station(s). At least one route must be defined.
				{from: "", to: ""},	// "from" is required but "to" is optional (set "to" to empty string to indicate all destinations)
			],
			skipMinutes: 0,		// Skip departures that happens within the next <value> minutes.
			maximumEntries: 6,	// Number of departures to show on screen
	                getRelative: 0,         // Show relative rather than absolute time when less than <valute> minutes left to departure, 0 = stay absolute
			truncateAfter: 5,	// A value > 0 will truncate direction name at first space after <value> characters. 0 = no truncation
			truncateLineAfter: 5,	// A value > 0 will truncate line number <value> characters. 0 = no truncation
	                showTrack: true,        // If true, track number will be displayed
                	coloredIcons: false,    // Setting this to true will color transportation type icons according to colors in colorTable
			apiKey: "MYAPIKEY"		// Your ResRobot apiKey
        }
    },
```

**Comment by Gwenadian** [comment]
It looks like you forgot to enter your API key. 

Edit: Trafiklab has capped the amount of information you can pull to 50/month. You can upgrade to Silver and get 250 requests per month.

**Comment by uFreke** [comment]
Have you fixed your problem @teddzoon? Have run into the same issue after years of working flawless.

The reguest you have as bronze user is the same as before what i can see. 10 000 request/month and 30/min.

**Comment by GooGit** [comment]
My ResRobot is stuck on Fetching departures too. Not sure why, maybe a API v2.1 issue? It works fine in browser and Postman though.

{
		module: "MMM-ResRobot",
		position: "left",
		header: "Avgångar",
		config: {
			routes: [
				{from: "740068883", to: ""},	// ResRobot Station IDs of starting and destination station(s). At least one route must be defined.
	//			{from: "", to: ""},	// "from" is required but "to" is optional (set "to" to empty string to indicate all destinations)
			],
			skipMinutes: 0,		// Skip departures that happens within the next <value> minutes.
			maximumEntries: 6,	// Number of departures to show on screen
	                getRelative: 0,         // Show relative rather than absolute time when less than <valute> minutes left to departure, 0 = stay absolute
			truncateAfter: 5,	// A value > 0 will truncate direction name at first space after <value> characters. 0 = no truncation
			truncateLineAfter: 5,	// A value > 0 will truncate line number <value> characters. 0 = no truncation
	                showTrack: true,        // If true, track number will be displayed
                	coloredIcons: false,    // Setting this to true will color transportation type icons according to colors in colorTable
			apiKey: "xxxxxx-xxxxx-xxxx-xxxx-xxxxxxx"		// commenting out my API key
        }

**Comment by Barracuda001** [comment]
I´m experiencing something either the same or similar. After a restart the module slowly fades on screen (while still updating the listings) untill it ends up on fetching departures. I thought it was related to fadetime so i changed it to false but no change, It´ll work great for a few hours, then need a restart of mm
