### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by petersbk** [Alvinger/MMM-ResRobot#2]
Hi, is it possible to have 2 instances, i.e. one showing buses, the other one showing subway

**Comment by O5ten** [comment]
Tried it out and i can verify that it does not work. It seems like they share the same node_helper shared between module instances. Tried but didn't manage to hash out how to split them yesterday. 

But i did manage to add a configuration option for specific transportTypes (trafikslag in swedish). 
See [this pull-request](https://github.com/Alvinger/MMM-ResRobot/pull/4) or clone the module from [my fork](https://github.com/O5ten/MMM-ResRobot/) if you need it.
