### ISSUE TITLE
Error: Cannot find module 'node-fetch'

### ISSUE THREAD

**Issue by alexbergsland** [Alvinger/MMM-ResRobot#22]
I messed up my MagicMirror install and is now reinstalling all my modules on a fresh Raspberry Pi.
When adding MMM-ResRobot I get `UnhandledPromiseRejectionWarning: Error: Cannot find module 'node-fetch'` which point to MMM-ResRobot needing this module.

After looking around I found this:
https://forum.magicmirror.builders/post/98964

So I changed node_helper.js from `const fetch = require("node-fetch");` to `const fetch = import("node-fetch");`
And then `npm install`.
I don't really understand what this does but it helped me.

**Comment by alexbergsland** [comment]
.. no, it made MagicMirror run but MMM-ResRobot is only showing `Fetching Departures ...`.
Now I have another error in the log.
`UnhandledPromiseRejectionWarning: TypeError: fetch is not a function`
But changing back to `require` gets me the same error as from the start and MM wont run at all.

**Comment by alexbergsland** [comment]
Ok, looking further I found this:
https://github.com/node-fetch/node-fetch#commonjs

I got it working by `npm uninstall node-fetch` and then `npm install node-fetch@2` and now MMM-ResRobot is showing departures. I don't really know what I am doing but I got it working.

**Comment by sdetweil** [comment]
this is because of 2 problems.
1. package.json dependencies lists fetch,
but the module needs node_fetch at version 2
2  we removed node_fetch from the mm package as node 18 and above (required) have fetch built in

the simplest fix is to comment out the require for node-fetch and let the code use the built in version of fetch

**Comment by emwtur** [comment]
> this is because of 2 problems.
> 
>     1. package.json dependencies lists fetch,
>        but the module needs node_fetch at version 2
>        2  we removed node_fetch from the mm package as node 18 and above (required) have fetch built in
> 
> 
> the simplest fix is to comment out the require for node-fetch and let the code use the built in version of fetch

removed the require in the node-helper.js did the trick for me 
Thanks
