### ISSUE TITLE
stuck on "fetching departures"

### ISSUE THREAD

**Issue by EB-EB-GIT** [Alvinger/MMM-ResRobot#5]
its stuck on fetching departures and dosent show any more than that

**Comment by Lavve** [comment]
My guess it's TrafikLab who's having some kind of issues on their side?

**Comment by el97** [comment]
I have the same issue...

**Comment by PseudoInsanity** [comment]
Anyone ever fixed this issue?

**Comment by el97** [comment]
This happens to me from time to time. Recently trafiklab had some problems with their servers and that have caused that the plugin isn't working. Keep in mind that you have to use "Pole Schedules 2" when you type in the API key.

**Comment by PseudoInsanity** [comment]
How do you mean? And if it's relevant, I'm trying to use the Skånetrafikens API if it makes a difference

**Comment by el97** [comment]
Oh... You'll have to use Resrobot API if you want it to work. each bus/train stop have their own location code so you can still use the module. Send me a PM if you need more help. @PseudoInsanity

**Comment by PseudoInsanity** [comment]
Ok is there a way to implement the Skånetrafiken API to the Resrobot API?

**Comment by PseudoInsanity** [comment]
never mind, solved it.
